layerhq/documentation

- guides/android/policies.md
- guides/ios/policies.md
- guides/ios/push-notification.md
- navigation.yaml
> Policies docs

- guides/android/richcontent.md
- guides/ios/richcontent.md
- quick-start/android/install.md
- transition/android/transition-guide.md
External content has been added for Android
> Externalcontent android

- guides/android/push-notification.md
- guides/ios/push-notification.md
- Changed images and documentation to match new Dashboard flow
> Updated Push Guides

- guides/android/push-notification.md
- integration/android/authentication.md
- integration/ios/authentication.md
> Updated Authentication Guide

- integration/android/authentication.md
- integration/ios/authentication.md
- Removed sample code from Integration -> Authentication
> Updated sample code

- integration/android/metadata.md
- integration/ios/metadata.md
> Metadata update

- integration/android/authentication.md
- integration/ios/authentication.md
- quick-start/android/authenticate.md
- quick-start/android/install.md
- quick-start/ios/authenticate.md
- Made Android guide compliant with v0.11.2
- Made iOS and Android match a bit better
- Cleaned up Authentication guides
> Documentation cleanup

- integration/android/installation-and-setup.md
- quick-start/android/install.md
`%%ANDROID-SDK-VERSION%%` for latest version of Android SDK
`%%IOS-SDK-VERSION%%` for latest version of iOS SDK.
> Added latest SDK version macro for android.

- ios/guides/push-integration.md
> Minor grammar and spelling changes

- ios/guides/advanced-querying.md
- ios/guides/atlas.md
- ios/guides/metadata.md
- ios/guides/parse.md
- ios/guides/push-integration.md
- ios/guides/push-notification.md
> spelling updates for iOS docs

- platform/platform-api/create-a-conversation.md
- platform/platform-api/send-a-message.md
> Spell checks Platform API docs

- android/guides/authentication.md
typo:
`Identity Tokens` are a pair pair of JSON dictionary structures
> update md file

- android/guides/push-integration.md
- android/integration/installation-and-setup.md
- android/quick-start/install.md
1. Corrected AndroidManifest.xml to reflect 0.16.0
2. Corrected gradle dependencies for both AAR and JAR to reflect 0.16.0
3. Added LayerClient.applicationCreated()
> Corrections for 0.16.0

- android/api/latest/data.json
[Historic synchronization](https://github.com/layerhq/releases-android/blob/master/releases/com/layer/sdk/layer-sdk/CHANGELOG.md#0170)
> Android API reference json updated

- client/rest/errors.md
Allow error urls to directly link to the relevant section
> Allow error urls to directly link to the relevant section

- client/introduction/authentication.md
Added extra `\` for line continuation
Removed extra `{` so -d is valid
> Fix curl command on /session

- platform/platform-api/edit-a-conversation.md
- platform/platform-api/overview.md
- platform/platform-api/send-a-message.md
- platform/platform-api/send-an-announcement.md
Curl command line breaks don't work with -d JSON body.
> Platform API curl command fixes

- android/api/latest/data.json
> Android API data.json updated

- client/CHANGELOG.md
- platform/platform-api/CHANGELOG.md
Placeholders only. Please add content.
> Added changelog files for Client and Platform API

- platform/platform-api/retrieve-a-conversation.md
* Adds documentation for fetching conversations for a specific user ID via the platform API.
> Adding docs for fetching conversations based on user ID

- platform/platform-api/create-a-conversation.md
Changes a 303 to 200 code for parity with the Client APIs where 303 responses caused unintended side-effects and had to be changed to 200.
> Changes 303 response to 200

- ios/integration/deleting.md
* Updating docs for new `My Devices` deletion mode.
> Changing deletion section title

- client/navigation.json
> Added Push Tokens section to navigation

- android/guides/push-notification.md
Changes to GCM's UI made old screenshots and instructions outdated. Changes include updating the step-by-step guide and refreshing the screenshots. @maju6406 @nilgradisnik
> Updated Android Push Notification Guide

- webhooks/introduction/overview.md
- webhooks/navigation.json
- webhooks/payloads/conversation-created.md
- webhooks/payloads/conversation-deleted.md
- webhooks/payloads/conversation-updated-metadata.md
- webhooks/payloads/conversation-updated-participants.md
- webhooks/payloads/message-deleted.md
- webhooks/payloads/message-delivered.md
- webhooks/payloads/message-read.md
- webhooks/payloads/message-sent.md
- webhooks/requests/overview.md
Updated navigation so that the REST API is at the bottom.
> Webhooks clarification about HTTP POST/GET requests

- ios/integration/authentication.md
- ios/integration/concepts.md
- ios/integration/deleting.md
- ios/integration/installation-and-setup.md
- ios/integration/metadata.md
- ios/integration/querying.md
- ios/integration/sending.md
- ios/integration/synchronization.md
Tweak grammar, standardize terminology, add details, etc
> Clarify content in iOS/Integration

- android/guides/parse.md
- android/quick-start/install.md
- android/quick-start/setup.md
- ios/atlas/parse.md
- ios/atlas/setup-atlas.md
- ios/integration/installation-and-setup.md
- ios/quick-start/install.md
- ios/quick-start/setup.md
> Remove $ prompts

- websdk/tutorials/conversations.md
> Fix typo in conversations.md
